### PR TITLE
Add glide dependency manager

### PR DESCRIPTION
**Pull request by pires**
In order to come up with #56 I had to build the code and adopting [`glide`](https://glide.sh/) made sense to me. Perhaps it will make sense to you too.

Thank you for your work!

### CODE REVIEW

**Comment by h0tbird** [comment]
After reading about the *vendoring* topic I understand the need for reproducible builds.
I don't like checking in the `/vendor` directory but I want a solution that is *goget-able*.
Let me dig more into this to get an idea.

**Comment by pires** [comment]
We can ditch the `vendor` directory and have people run `glide install`.

**Comment by pires** [comment]
Actually, preparing for that, I committed the `vendor` directory separately so it's easier to drop the commit.

**Comment by h0tbird** [comment]
Go ahead and drop the `vendor` for now. I need some time to understand pros and cons.
Thank you!

**Comment by pires** [comment]
I think the only con is having more noise in PR diffs when one changes dependencies. Other than that, it actually helps users because they don't need to care about installing `glide`. It will just work with Go > 1.6.

**Comment by h0tbird** [comment]
I am now using `dep` for dependency management.

**Pull request closed without merging**
